//! IPC surface. Command names are the contract with `src/lib/ipc.ts`; keep both in sync.

pub mod accounts;
pub mod checkpoints;
pub mod env;
pub mod fs;
pub mod git;
pub mod preview;
pub mod github;
pub mod projects;
pub mod pty;
pub mod selfbuild;
pub mod sessions;
pub mod settings;
pub mod tools;
pub mod usage;

pub fn handler() -> impl Fn(tauri::ipc::Invoke) -> bool + Send + Sync + 'static {
    tauri::generate_handler![
        accounts::accounts_list,
        accounts::accounts_create,
        accounts::accounts_remove,
        accounts::accounts_project_get,
        accounts::accounts_project_set,
        accounts::accounts_session_get,
        settings::settings_get,
        settings::settings_set,
        tools::tools_detect,
        tools::tools_auth_status,
        tools::models_list,
        tools::tools_install,
        tools::tools_login_start,
        tools::tools_login_code,
        tools::tools_login_cancel,
        env::env_ssh_key_info,
        env::env_ssh_generate_key,
        env::env_ssh_test_github,
        projects::projects_list,
        projects::projects_get,
        projects::projects_create,
        projects::projects_open,
        projects::projects_rename,
        projects::projects_update,
        projects::projects_remote_status,
        projects::projects_remove,
        projects::stacks_list,
        projects::stacks_recommend,
        projects::stacks_ai_recommend,
        projects::projects_agent_docs_status,
        projects::projects_generate_agent_docs,
        projects::projects_sync_agent_docs,
        projects::projects_ai_plan,
        projects::projects_export_name,
        projects::projects_export,
        usage::usage_history,
        usage::usage_latest,
        usage::usage_refresh,
        selfbuild::self_build_info,
        selfbuild::self_build_run,
        selfbuild::self_build_apply,
        sessions::session_start,
        sessions::session_send,
        sessions::session_interrupt,
        sessions::session_permission_reply,
        sessions::session_update_config,
        sessions::session_close,
        sessions::sessions_list,
        sessions::session_messages,
        sessions::session_delete,
        sessions::session_answer_question,
        sessions::session_rename,
        sessions::session_set_archived,
        sessions::session_export_markdown,
        sessions::session_export_to_file,
        checkpoints::checkpoints_list,
        checkpoints::checkpoint_create,
        checkpoints::checkpoint_restore,
        checkpoints::checkpoint_diff,
        fs::fs_list,
        fs::fs_read,
        preview::preview_open,
        preview::preview_set_bounds,
        preview::preview_set_visible,
        preview::preview_close,
        preview::preview_reload,
        preview::preview_eval,
        preview::preview_server_start,
        preview::preview_server_stop,
        preview::preview_server_status,
        git::git_status,
        git::git_init,
        git::git_diff,
        git::git_stage,
        git::git_unstage,
        git::git_commit,
        git::git_push,
        git::git_pull,
        git::git_fetch,
        git::git_branches,
        git::git_checkout,
        git::git_log,
        git::git_generate_commit_message,
        github::github_set_token,
        github::github_clear_token,
        github::github_whoami,
        github::github_create_repo,
        pty::pty_open,
        pty::pty_write,
        pty::pty_resize,
        pty::pty_close,
    ]
}
