// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountKind } from "./AccountKind";

export type AccountProfile = { id: string, name: string, kind: AccountKind, };
