// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QuestionOption } from "./QuestionOption";

export type AgentQuestion = { id: string, 
/**
 * Short chip/tag, e.g. "Auth method".
 */
header: string, question: string, options: Array<QuestionOption>, multi_select: boolean, allow_free_text: boolean, };
