// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which agent instruction files exist in a project directory.
 */
export type AgentDocsStatus = { claude_md: boolean, agents_md: boolean, };
