// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackendConfig } from "./BackendConfig";
import type { Effort } from "./Effort";
import type { PermissionPreset } from "./PermissionPreset";
import type { Provider } from "./Provider";

export type AppSettings = { backend: BackendConfig, default_provider: Provider, default_model_claude?: string | null, default_model_codex?: string | null, default_effort: Effort, default_permission: PermissionPreset, 
/**
 * Windows path where new projects are created by default.
 */
projects_root?: string | null, 
/**
 * Explicit binary overrides (host or backend path). Empty = auto-detect.
 */
claude_bin?: string | null, codex_bin?: string | null, git_bin?: string | null, 
/**
 * Commit author used for git commits made by the app (passed as `-c user.name/user.email`).
 */
git_user_name?: string | null, git_user_email?: string | null, theme: string, onboarding_done: boolean, };
