// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Provider } from "./Provider";

export type AuthStatus = { provider: Provider, logged_in: boolean, method?: string | null, account?: string | null, detail?: string | null, };
