// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the app does with the project's working tree after every agent turn (see `git::auto`).
 */
export type AutoGit = "off" | "commit" | "commit_push";
