// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackendKind } from "./BackendKind";

/**
 * Where commands run. `wsl_distro = None` with `Wsl` means the default distro.
 */
export type BackendConfig = { kind: BackendKind, wsl_distro?: string | null, };
