// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CheckpointRecord = { id: string, project_id: string, session_id?: string | null, 
/**
 * Monotonic per project.
 */
seq: number, 
/**
 * Commit hash of the snapshot tree.
 */
git_ref: string, label: string, created_at: string, };
