// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Effort } from "./Effort";
import type { PermissionPreset } from "./PermissionPreset";
import type { ProjectType } from "./ProjectType";
import type { Provider } from "./Provider";
import type { TargetOs } from "./TargetOs";

export type CreateProjectRequest = { name: string, 
/**
 * Parent directory (Windows path). Project dir = parent/name.
 */
parent_dir: string, target_os: TargetOs, project_type: ProjectType, stack_id?: string | null, description: string, git_init: boolean, create_github_repo: boolean, github_private: boolean, generate_agent_docs: boolean, default_provider?: Provider | null, default_model?: string | null, default_effort?: Effort | null, default_permission?: PermissionPreset | null, };
