// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Effort } from "./Effort";
import type { PermissionPreset } from "./PermissionPreset";
import type { ProjectAccounts } from "./ProjectAccounts";
import type { ProjectType } from "./ProjectType";
import type { Provider } from "./Provider";
import type { TargetOs } from "./TargetOs";

export type CreateProjectRequest = { accounts: ProjectAccounts, 
/**
 * Display name shown in the app (any characters incl. Korean).
 */
name: string, 
/**
 * Folder / package identifier used by scaffolding tools (ASCII: a-z 0-9 - _ .). None = derived from `name`
 * when that is already a valid identifier.
 */
dir_name?: string | null, 
/**
 * Parent directory (Windows path). Project dir = parent/dir_name.
 */
parent_dir: string, target_os: TargetOs, project_type: ProjectType, stack_id?: string | null, description: string, git_init: boolean, create_github_repo: boolean, github_private: boolean, generate_agent_docs: boolean, 
/**
 * Install missing prerequisites before scaffolding: Windows toolchains with winget on the host,
 * backend-side tools with their install hints. Progress arrives as `ScaffoldEvent::Install`.
 */
install_missing_tools: boolean, default_provider?: Provider | null, default_model?: string | null, default_effort?: Effort | null, default_permission?: PermissionPreset | null, };
