// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Unified effort scale. Adapters map it to provider-specific values:
 * Claude: low/medium/high/xhigh/max (minimal -> low)
 * Codex:  minimal/low/medium/high/xhigh (max -> xhigh)
 */
export type Effort = "minimal" | "low" | "medium" | "high" | "xhigh" | "max";
