// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Progress of `projects_export` (also used by the self-build).
 */
export type ExportEvent = { "type": "step", name: string, } | { "type": "log", line: string, is_err: boolean, } | { "type": "done", path: string, size_bytes: number, files: number, } | { "type": "failed", message: string, };
