// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FsEntry = { name: string, 
/**
 * Path relative to the project root, forward slashes.
 */
rel_path: string, is_dir: boolean, size: number, modified?: string | null, 
/**
 * Matches a common ignore pattern (node_modules, target, .git, ...); shown dimmed and not expanded by default.
 */
ignored: boolean, };
