// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FsFile = { rel_path: string, content: string, size: number, truncated: boolean, binary: boolean, };
