// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GitFileStatus = { path: string, 
/**
 * Two-letter porcelain code, e.g. " M", "M ", "??", "A ", "D ".
 */
code: string, staged: boolean, unstaged: boolean, untracked: boolean, };
