// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GitHubRepo = { full_name: string, html_url: string, ssh_url: string, clone_url: string, private: boolean, };
