// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Outcome of one automatic install.
 */
export type InstallStatus = "running" | "done" | "failed" | "skipped";
