// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where an automatically installed tool lives.
 */
export type InstallKind = "windows_toolchain" | "backend_tool";
