// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Progress of a GUI login (`claude auth login` / `codex login` running in a hidden PTY).
 */
export type LoginEvent = { "type": "started" } | { "type": "url", url: string, } | { "type": "code_requested" } | { "type": "output", line: string, } | { "type": "finished", code?: number | null, logged_in: boolean, account?: string | null, };
