// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EnvVar } from "./EnvVar";
import type { McpTransport } from "./McpTransport";
import type { Provider } from "./Provider";

/**
 * One MCP server definition, written into Claude's `--mcp-config` and Codex's config.
 */
export type McpServerConfig = { id: string, 
/**
 * Server name as the agents see it (tool prefix `mcp__<name>__`).
 */
name: string, transport: McpTransport, command?: string | null, args: Array<string>, env: Array<EnvVar>, url?: string | null, enabled: boolean, 
/**
 * Which agents receive this server (empty = both).
 */
providers: Array<Provider>, };
