// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageKind } from "./MessageKind";

export type MessageRecord = { id: string, session_id: string, seq: number, kind: MessageKind, payload: unknown, created_at: string, };
