// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Effort } from "./Effort";
import type { Provider } from "./Provider";

export type ModelInfo = { provider: Provider, id: string, label: string, 
/**
 * Efforts the provider reports as supported for this model (unified scale).
 */
efforts: Array<Effort>, is_default: boolean, };
