// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionDecision } from "./PermissionDecision";

export type PermissionReply = { request_id: string, decision: PermissionDecision, message?: string | null, };
