// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Unified permission presets (see docs/PLAN.md 3.3).
 * Claude: plan / manual / acceptEdits / bypassPermissions
 * Codex:  read-only+untrusted / workspace-write+on-request / workspace-write+on-request / danger-full-access+never
 */
export type PermissionPreset = "read_only" | "ask_everything" | "auto_edit" | "full_auto";
