// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlanStep = { text: string, 
/**
 * "pending" | "in_progress" | "completed"
 */
status: string, };
