// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PreviewEvent = { "type": "started", command: string, } | { "type": "log", line: string, is_err: boolean, } | { "type": "url", url: string, } | { "type": "exited", code?: number | null, };
