// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PreviewStatus = { running: boolean, command?: string | null, url?: string | null, };
