// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProjectAccounts = { claude?: string | null, codex?: string | null, github?: string | null, git_user_name?: string | null, git_user_email?: string | null, };
