// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectType } from "./ProjectType";
import type { TargetOs } from "./TargetOs";
import type { ToolStatus } from "./ToolStatus";

export type ProjectPlan = { name: string, dir_name: string, target_os: TargetOs, project_type: ProjectType, 
/**
 * None = empty project (no scaffold).
 */
stack_id?: string | null, 
/**
 * One-sentence Korean summary of the project purpose.
 */
summary: string, 
/**
 * Why this configuration was chosen (Korean, 1-2 sentences).
 */
reason: string, 
/**
 * Backend-side prerequisites of the chosen stack that are not installed.
 */
missing_tools: Array<ToolStatus>, };
