// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProjectType = "desktop_app" | "web_app" | "mobile_app" | "cli" | "api_server" | "library" | "game" | "script";
