// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutoGit } from "./AutoGit";
import type { Effort } from "./Effort";
import type { PermissionPreset } from "./PermissionPreset";
import type { ProjectType } from "./ProjectType";
import type { Provider } from "./Provider";
import type { TargetOs } from "./TargetOs";

export type ProjectRecord = { id: string, name: string, 
/**
 * Windows (host) path.
 */
path: string, target_os?: TargetOs | null, project_type?: ProjectType | null, stack_id?: string | null, github_url?: string | null, default_provider?: Provider | null, default_model?: string | null, default_effort?: Effort | null, default_permission?: PermissionPreset | null, 
/**
 * None = follow `AppSettings.auto_git`.
 */
auto_git?: AutoGit | null, created_at: string, last_opened_at: string, };
