// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Provider } from "./Provider";

/**
 * "Describe it in one line" project creation: the agent picks everything.
 */
export type ProjectPlanRequest = { account_id?: string | null, description: string, 
/**
 * Windows path the project will be created in (used to pick a free folder name). Empty = skip the check.
 */
parent_dir: string, provider: Provider, };
