// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Effort } from "./Effort";
import type { PermissionPreset } from "./PermissionPreset";
import type { ProjectAccounts } from "./ProjectAccounts";
import type { Provider } from "./Provider";

export type ProjectSettingsUpdate = { name: string, accounts: ProjectAccounts, default_provider: Provider, default_model: string | null, default_effort: Effort | null, default_permission: PermissionPreset, 
/**
 * Only change origin when the user edits the repository connection.
 */
update_remote: boolean, remote_url: string | null, };
