// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProvisionEvent = { "type": "step", name: string, } | { "type": "log", line: string, is_err: boolean, } | { "type": "progress", bytes: number, total?: number | null, } | { "type": "done" } | { "type": "failed", message: string, };
