// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PtySpec = { 
/**
 * Program to run; None = interactive PowerShell.
 */
program?: string | null, args: Array<string>, 
/**
 * Windows path.
 */
cwd?: string | null, cols: number, rows: number, };
