// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A question the agent asks the user (Claude AskUserQuestion / Codex requestUserInput).
 */
export type QuestionOption = { label: string, description?: string | null, };
