// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One subscription rate-limit window as reported by a CLI
 * (Claude: 5-hour session / 7-day weekly; Codex: primary / secondary).
 */
export type RateLimitWindow = { 
/**
 * Stable id: "five_hour" | "seven_day" | "seven_day_overage_included" | "primary" | "secondary".
 */
id: string, 
/**
 * Korean label for the UI ("5시간", "1주일").
 */
label: string, 
/**
 * 0..100
 */
used_percent: number, 
/**
 * Unix epoch seconds when the window resets.
 */
resets_at?: number | null, 
/**
 * Window length in minutes when the provider reports it.
 */
window_minutes?: number | null, };
