// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectRecord } from "./ProjectRecord";

export type ScaffoldEvent = { "type": "step", name: string, } | { "type": "log", line: string, is_err: boolean, } | { "type": "done", project: ProjectRecord, } | { "type": "failed", message: string, };
