// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstallKind } from "./InstallKind";
import type { InstallStatus } from "./InstallStatus";
import type { ProjectRecord } from "./ProjectRecord";

export type ScaffoldEvent = { "type": "step", name: string, } | { "type": "log", line: string, is_err: boolean, } | { "type": "install", 
/**
 * Tool name (toolchain: rust, msvc, node …; backend tool: uv, python, npm …).
 */
name: string, label: string, kind: InstallKind, 
/**
 * 1-based position in this creation's install list.
 */
index: number, total: number, status: InstallStatus, 
/**
 * Version after a successful install, or why it failed / was skipped.
 */
message: string | null, 
/**
 * Command that was (or should be) run, for a manual retry in a terminal.
 */
command: string | null, } | { "type": "done", project: ProjectRecord, } | { "type": "failed", message: string, };
