// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What "새 빌드 적용" would do (see `selfbuild`).
 */
export type SelfBuildInfo = { 
/**
 * Source checkout, when found.
 */
repo?: string | null, 
/**
 * Path of the running executable (the file that gets replaced).
 */
current_exe: string, 
/**
 * Where the build writes the new executable.
 */
build_output?: string | null, 
/**
 * The running exe is the build output itself: build must happen after the app exits.
 */
in_place: boolean, build_command: string, };
