// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Effort } from "./Effort";
import type { PermissionPreset } from "./PermissionPreset";
import type { Provider } from "./Provider";

export type SessionConfig = { project_id: string, provider: Provider, model?: string | null, effort?: Effort | null, permission: PermissionPreset, append_system_prompt?: string | null, 
/**
 * Resume an existing provider session/thread (Claude session_id or Codex thread id).
 */
resume_ref?: string | null, fork: boolean, };
