// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Effort } from "./Effort";
import type { PermissionPreset } from "./PermissionPreset";

/**
 * Fields that may change between turns without restarting the session.
 */
export type SessionConfigPatch = { model?: string | null, effort?: Effort | null, permission?: PermissionPreset | null, };
