// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Effort } from "./Effort";
import type { PermissionPreset } from "./PermissionPreset";
import type { Provider } from "./Provider";

export type SessionRecord = { id: string, project_id: string, provider: Provider, 
/**
 * Provider-side id used for resume (Claude session_id / Codex thread id).
 */
external_ref?: string | null, title: string, model?: string | null, effort?: Effort | null, permission: PermissionPreset, total_cost_usd: number, 
/**
 * Hidden from the default session list.
 */
archived: boolean, created_at: string, last_used_at: string, };
