// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExportFormat } from "./ExportFormat";

/**
 * Build-and-package recipe of a stack (`[stack.export]` in stacks.toml).
 */
export type StackExport = { 
/**
 * What the user gets, e.g. "Windows 실행 파일 (portable zip)".
 */
label: string, 
/**
 * Shell command run in the project directory before collecting artifacts; `{name}` = folder name.
 */
build_command?: string | null, 
/**
 * Glob patterns relative to the project directory (forward slashes).
 */
artifacts: Array<string>, format: ExportFormat, 
/**
 * Extension of the exported file without the dot ("zip", "exe", "apk").
 */
extension: string, 
/**
 * Hint shown before exporting (runtime requirements, expected duration).
 */
note?: string | null, };
