// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectType } from "./ProjectType";
import type { TargetOs } from "./TargetOs";

export type StackInfo = { id: string, name: string, summary: string, targets: Array<TargetOs>, types: Array<ProjectType>, languages: Array<string>, 
/**
 * Shell command executed inside the new project directory's parent. `{name}` is replaced.
 */
scaffold_cmd?: string | null, 
/**
 * Tool names (see ToolStatus.name) that must be present.
 */
prerequisites: Array<string>, pros: Array<string>, cons: Array<string>, recommended: boolean, 
/**
 * Extra notes for CLAUDE.md / AGENTS.md (build/test commands, conventions).
 */
agent_notes?: string | null, 
/**
 * Command that starts a dev server whose URL can be shown in the UI preview (None = not a web UI).
 */
dev_command?: string | null, 
/**
 * Windows-side toolchains (see `toolchain::WIN_TOOLS` names: rust, msvc, node, dotnet, go) needed when the
 * agent works inside WSL but the build output must be a Windows program. Empty = builds fine on the backend.
 */
windows_toolchain: Array<string>, };
