// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StackRecommendation = { stack_id: string, 
/**
 * 0-100
 */
score: number, reason: string, };
