// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectType } from "./ProjectType";
import type { Provider } from "./Provider";
import type { TargetOs } from "./TargetOs";

export type StackRecommendRequest = { description: string, target_os: TargetOs, project_type: ProjectType, provider: Provider, };
