// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ToolStatus = { 
/**
 * e.g. "claude", "codex", "git", "node", "npm", "cargo", "rustup", "python", "flutter", "dotnet", "gh"
 */
name: string, found: boolean, path?: string | null, version?: string | null, 
/**
 * Human-readable install hint for the active backend.
 */
install_hint?: string | null, };
