// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolStatus } from "./ToolStatus";

/**
 * Progress of a GUI tool install (`tools_install`).
 */
export type ToolInstallEvent = { "type": "log", line: string, is_err: boolean, } | { "type": "finished", ok: boolean, message: string, status: ToolStatus, };
