// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Provider } from "./Provider";
import type { RateLimitWindow } from "./RateLimitWindow";

/**
 * A persisted usage observation (one row per window per report), for the usage graph.
 */
export type UsageSample = { provider: Provider, account_id?: string | null, window: RateLimitWindow, 
/**
 * Unix epoch seconds.
 */
observed_at: number, };
