// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WindowsToolStatus = { 
/**
 * rust | msvc | node | dotnet | go
 */
name: string, label: string, found: boolean, 
/**
 * Windows path of the main executable (or install dir for msvc).
 */
path?: string | null, version?: string | null, 
/**
 * winget package id.
 */
winget_id: string, 
/**
 * Shim names created in the WSL distro (`~/.local/bin`), e.g. cargo.exe, npm.cmd.
 */
shims: Array<string>, };
