// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WslState } from "./WslState";

export type WslStatus = { state: WslState, version?: string | null, distros: Array<string>, 
/**
 * Name of the app-owned distribution.
 */
managed_distro: string, managed_present: boolean, 
/**
 * Present and the provisioning marker + tools check passed.
 */
managed_ready: boolean, detail?: string | null, 
/**
 * Windows build number (WSL2 needs 19041+). 0 = unknown.
 */
windows_build: number, 
/**
 * CPU virtualization available to Windows: true when a hypervisor is already running or the
 * firmware reports it enabled; false when the BIOS/UEFI setting is off; None = unknown.
 */
virtualization_enabled?: boolean | null, hypervisor_present: boolean, cpu_vendor?: string | null, };
